# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(818, 685)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_26 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.frame_9 = QtGui.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_23 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_23.setMargin(0)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.cell_6_0 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_0.sizePolicy().hasHeightForWidth())
        self.cell_6_0.setSizePolicy(sizePolicy)
        self.cell_6_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_0.setObjectName(_fromUtf8("cell_6_0"))
        self.gridLayout_23.addWidget(self.cell_6_0, 0, 0, 1, 1)
        self.cell_6_1 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_1.sizePolicy().hasHeightForWidth())
        self.cell_6_1.setSizePolicy(sizePolicy)
        self.cell_6_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_1.setObjectName(_fromUtf8("cell_6_1"))
        self.gridLayout_23.addWidget(self.cell_6_1, 0, 1, 1, 1)
        self.cell_7_1 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_1.sizePolicy().hasHeightForWidth())
        self.cell_7_1.setSizePolicy(sizePolicy)
        self.cell_7_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_1.setObjectName(_fromUtf8("cell_7_1"))
        self.gridLayout_23.addWidget(self.cell_7_1, 1, 1, 1, 1)
        self.cell_7_0 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_0.sizePolicy().hasHeightForWidth())
        self.cell_7_0.setSizePolicy(sizePolicy)
        self.cell_7_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_0.setObjectName(_fromUtf8("cell_7_0"))
        self.gridLayout_23.addWidget(self.cell_7_0, 1, 0, 1, 1)
        self.cell_8_0 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_0.sizePolicy().hasHeightForWidth())
        self.cell_8_0.setSizePolicy(sizePolicy)
        self.cell_8_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_0.setObjectName(_fromUtf8("cell_8_0"))
        self.gridLayout_23.addWidget(self.cell_8_0, 2, 0, 1, 1)
        self.cell_8_2 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_2.sizePolicy().hasHeightForWidth())
        self.cell_8_2.setSizePolicy(sizePolicy)
        self.cell_8_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_2.setObjectName(_fromUtf8("cell_8_2"))
        self.gridLayout_23.addWidget(self.cell_8_2, 2, 2, 1, 1)
        self.cell_8_1 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_1.sizePolicy().hasHeightForWidth())
        self.cell_8_1.setSizePolicy(sizePolicy)
        self.cell_8_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_1.setObjectName(_fromUtf8("cell_8_1"))
        self.gridLayout_23.addWidget(self.cell_8_1, 2, 1, 1, 1)
        self.cell_6_2 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_2.sizePolicy().hasHeightForWidth())
        self.cell_6_2.setSizePolicy(sizePolicy)
        self.cell_6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_2.setObjectName(_fromUtf8("cell_6_2"))
        self.gridLayout_23.addWidget(self.cell_6_2, 0, 2, 1, 1)
        self.cell_7_2 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_2.sizePolicy().hasHeightForWidth())
        self.cell_7_2.setSizePolicy(sizePolicy)
        self.cell_7_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_2.setObjectName(_fromUtf8("cell_7_2"))
        self.gridLayout_23.addWidget(self.cell_7_2, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_9, 2, 0, 1, 1)
        self.frame_10 = QtGui.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.gridLayout_24 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_24.setMargin(0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.cell_6_3 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_3.sizePolicy().hasHeightForWidth())
        self.cell_6_3.setSizePolicy(sizePolicy)
        self.cell_6_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_3.setObjectName(_fromUtf8("cell_6_3"))
        self.gridLayout_24.addWidget(self.cell_6_3, 0, 0, 1, 1)
        self.cell_6_4 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_4.sizePolicy().hasHeightForWidth())
        self.cell_6_4.setSizePolicy(sizePolicy)
        self.cell_6_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_4.setObjectName(_fromUtf8("cell_6_4"))
        self.gridLayout_24.addWidget(self.cell_6_4, 0, 1, 1, 1)
        self.cell_7_4 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_4.sizePolicy().hasHeightForWidth())
        self.cell_7_4.setSizePolicy(sizePolicy)
        self.cell_7_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_4.setObjectName(_fromUtf8("cell_7_4"))
        self.gridLayout_24.addWidget(self.cell_7_4, 1, 1, 1, 1)
        self.cell_7_3 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_3.sizePolicy().hasHeightForWidth())
        self.cell_7_3.setSizePolicy(sizePolicy)
        self.cell_7_3.setText(_fromUtf8(""))
        self.cell_7_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_3.setObjectName(_fromUtf8("cell_7_3"))
        self.gridLayout_24.addWidget(self.cell_7_3, 1, 0, 1, 1)
        self.cell_8_3 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_3.sizePolicy().hasHeightForWidth())
        self.cell_8_3.setSizePolicy(sizePolicy)
        self.cell_8_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_3.setObjectName(_fromUtf8("cell_8_3"))
        self.gridLayout_24.addWidget(self.cell_8_3, 2, 0, 1, 1)
        self.cell_8_5 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_5.sizePolicy().hasHeightForWidth())
        self.cell_8_5.setSizePolicy(sizePolicy)
        self.cell_8_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_5.setObjectName(_fromUtf8("cell_8_5"))
        self.gridLayout_24.addWidget(self.cell_8_5, 2, 2, 1, 1)
        self.cell_8_4 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_4.sizePolicy().hasHeightForWidth())
        self.cell_8_4.setSizePolicy(sizePolicy)
        self.cell_8_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_4.setObjectName(_fromUtf8("cell_8_4"))
        self.gridLayout_24.addWidget(self.cell_8_4, 2, 1, 1, 1)
        self.cell_6_5 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_5.sizePolicy().hasHeightForWidth())
        self.cell_6_5.setSizePolicy(sizePolicy)
        self.cell_6_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_5.setObjectName(_fromUtf8("cell_6_5"))
        self.gridLayout_24.addWidget(self.cell_6_5, 0, 2, 1, 1)
        self.cell_7_5 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_5.sizePolicy().hasHeightForWidth())
        self.cell_7_5.setSizePolicy(sizePolicy)
        self.cell_7_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_5.setObjectName(_fromUtf8("cell_7_5"))
        self.gridLayout_24.addWidget(self.cell_7_5, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_10, 2, 1, 1, 1)
        self.frame_6 = QtGui.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_20.setMargin(0)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.cell_3_0 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_0.sizePolicy().hasHeightForWidth())
        self.cell_3_0.setSizePolicy(sizePolicy)
        self.cell_3_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_0.setObjectName(_fromUtf8("cell_3_0"))
        self.gridLayout_20.addWidget(self.cell_3_0, 0, 0, 1, 1)
        self.cell_3_1 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_1.sizePolicy().hasHeightForWidth())
        self.cell_3_1.setSizePolicy(sizePolicy)
        self.cell_3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_1.setObjectName(_fromUtf8("cell_3_1"))
        self.gridLayout_20.addWidget(self.cell_3_1, 0, 1, 1, 1)
        self.cell_4_1 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_1.sizePolicy().hasHeightForWidth())
        self.cell_4_1.setSizePolicy(sizePolicy)
        self.cell_4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_1.setObjectName(_fromUtf8("cell_4_1"))
        self.gridLayout_20.addWidget(self.cell_4_1, 1, 1, 1, 1)
        self.cell_4_0 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_0.sizePolicy().hasHeightForWidth())
        self.cell_4_0.setSizePolicy(sizePolicy)
        self.cell_4_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_0.setObjectName(_fromUtf8("cell_4_0"))
        self.gridLayout_20.addWidget(self.cell_4_0, 1, 0, 1, 1)
        self.cell_5_0 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_0.sizePolicy().hasHeightForWidth())
        self.cell_5_0.setSizePolicy(sizePolicy)
        self.cell_5_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_0.setObjectName(_fromUtf8("cell_5_0"))
        self.gridLayout_20.addWidget(self.cell_5_0, 2, 0, 1, 1)
        self.cell_5_2 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_2.sizePolicy().hasHeightForWidth())
        self.cell_5_2.setSizePolicy(sizePolicy)
        self.cell_5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_2.setObjectName(_fromUtf8("cell_5_2"))
        self.gridLayout_20.addWidget(self.cell_5_2, 2, 2, 1, 1)
        self.cell_5_1 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_1.sizePolicy().hasHeightForWidth())
        self.cell_5_1.setSizePolicy(sizePolicy)
        self.cell_5_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_1.setObjectName(_fromUtf8("cell_5_1"))
        self.gridLayout_20.addWidget(self.cell_5_1, 2, 1, 1, 1)
        self.cell_3_2 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_2.sizePolicy().hasHeightForWidth())
        self.cell_3_2.setSizePolicy(sizePolicy)
        self.cell_3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_2.setObjectName(_fromUtf8("cell_3_2"))
        self.gridLayout_20.addWidget(self.cell_3_2, 0, 2, 1, 1)
        self.cell_4_2 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_2.sizePolicy().hasHeightForWidth())
        self.cell_4_2.setSizePolicy(sizePolicy)
        self.cell_4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_2.setObjectName(_fromUtf8("cell_4_2"))
        self.gridLayout_20.addWidget(self.cell_4_2, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_18 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.cell_0_3 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_3.sizePolicy().hasHeightForWidth())
        self.cell_0_3.setSizePolicy(sizePolicy)
        self.cell_0_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_3.setObjectName(_fromUtf8("cell_0_3"))
        self.gridLayout_18.addWidget(self.cell_0_3, 0, 0, 1, 1)
        self.cell_0_4 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_4.sizePolicy().hasHeightForWidth())
        self.cell_0_4.setSizePolicy(sizePolicy)
        self.cell_0_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_4.setObjectName(_fromUtf8("cell_0_4"))
        self.gridLayout_18.addWidget(self.cell_0_4, 0, 1, 1, 1)
        self.cell_1_4 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_4.sizePolicy().hasHeightForWidth())
        self.cell_1_4.setSizePolicy(sizePolicy)
        self.cell_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_4.setObjectName(_fromUtf8("cell_1_4"))
        self.gridLayout_18.addWidget(self.cell_1_4, 1, 1, 1, 1)
        self.cell_1_3 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_3.sizePolicy().hasHeightForWidth())
        self.cell_1_3.setSizePolicy(sizePolicy)
        self.cell_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_3.setObjectName(_fromUtf8("cell_1_3"))
        self.gridLayout_18.addWidget(self.cell_1_3, 1, 0, 1, 1)
        self.cell_2_3 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_3.sizePolicy().hasHeightForWidth())
        self.cell_2_3.setSizePolicy(sizePolicy)
        self.cell_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_3.setObjectName(_fromUtf8("cell_2_3"))
        self.gridLayout_18.addWidget(self.cell_2_3, 2, 0, 1, 1)
        self.cell_2_5 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_5.sizePolicy().hasHeightForWidth())
        self.cell_2_5.setSizePolicy(sizePolicy)
        self.cell_2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_5.setObjectName(_fromUtf8("cell_2_5"))
        self.gridLayout_18.addWidget(self.cell_2_5, 2, 2, 1, 1)
        self.cell_2_4 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_4.sizePolicy().hasHeightForWidth())
        self.cell_2_4.setSizePolicy(sizePolicy)
        self.cell_2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_4.setObjectName(_fromUtf8("cell_2_4"))
        self.gridLayout_18.addWidget(self.cell_2_4, 2, 1, 1, 1)
        self.cell_0_5 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_5.sizePolicy().hasHeightForWidth())
        self.cell_0_5.setSizePolicy(sizePolicy)
        self.cell_0_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_5.setObjectName(_fromUtf8("cell_0_5"))
        self.gridLayout_18.addWidget(self.cell_0_5, 0, 2, 1, 1)
        self.cell_1_5 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_5.sizePolicy().hasHeightForWidth())
        self.cell_1_5.setSizePolicy(sizePolicy)
        self.cell_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_5.setObjectName(_fromUtf8("cell_1_5"))
        self.gridLayout_18.addWidget(self.cell_1_5, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_4, 0, 1, 1, 1)
        self.frame_11 = QtGui.QFrame(self.frame_2)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout_25 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_25.setMargin(0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.cell_8_8 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_8.sizePolicy().hasHeightForWidth())
        self.cell_8_8.setSizePolicy(sizePolicy)
        self.cell_8_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_8.setObjectName(_fromUtf8("cell_8_8"))
        self.gridLayout_25.addWidget(self.cell_8_8, 2, 2, 1, 1)
        self.cell_8_7 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_7.sizePolicy().hasHeightForWidth())
        self.cell_8_7.setSizePolicy(sizePolicy)
        self.cell_8_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_7.setObjectName(_fromUtf8("cell_8_7"))
        self.gridLayout_25.addWidget(self.cell_8_7, 2, 1, 1, 1)
        self.cell_7_6 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_6.sizePolicy().hasHeightForWidth())
        self.cell_7_6.setSizePolicy(sizePolicy)
        self.cell_7_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_6.setObjectName(_fromUtf8("cell_7_6"))
        self.gridLayout_25.addWidget(self.cell_7_6, 1, 0, 1, 1)
        self.cell_7_8 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_8.sizePolicy().hasHeightForWidth())
        self.cell_7_8.setSizePolicy(sizePolicy)
        self.cell_7_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_8.setObjectName(_fromUtf8("cell_7_8"))
        self.gridLayout_25.addWidget(self.cell_7_8, 1, 2, 1, 1)
        self.cell_6_8 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_8.sizePolicy().hasHeightForWidth())
        self.cell_6_8.setSizePolicy(sizePolicy)
        self.cell_6_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_8.setObjectName(_fromUtf8("cell_6_8"))
        self.gridLayout_25.addWidget(self.cell_6_8, 0, 2, 1, 1)
        self.cell_7_7 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_7.sizePolicy().hasHeightForWidth())
        self.cell_7_7.setSizePolicy(sizePolicy)
        self.cell_7_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_7_7.setObjectName(_fromUtf8("cell_7_7"))
        self.gridLayout_25.addWidget(self.cell_7_7, 1, 1, 1, 1)
        self.cell_8_6 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_6.sizePolicy().hasHeightForWidth())
        self.cell_8_6.setSizePolicy(sizePolicy)
        self.cell_8_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_8_6.setObjectName(_fromUtf8("cell_8_6"))
        self.gridLayout_25.addWidget(self.cell_8_6, 2, 0, 1, 1)
        self.cell_6_7 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_7.sizePolicy().hasHeightForWidth())
        self.cell_6_7.setSizePolicy(sizePolicy)
        self.cell_6_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_7.setObjectName(_fromUtf8("cell_6_7"))
        self.gridLayout_25.addWidget(self.cell_6_7, 0, 1, 1, 1)
        self.cell_6_6 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_6.sizePolicy().hasHeightForWidth())
        self.cell_6_6.setSizePolicy(sizePolicy)
        self.cell_6_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_6_6.setObjectName(_fromUtf8("cell_6_6"))
        self.gridLayout_25.addWidget(self.cell_6_6, 0, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame_11, 2, 2, 1, 1)
        self.frame_7 = QtGui.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_21.setMargin(0)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.cell_3_5 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_5.sizePolicy().hasHeightForWidth())
        self.cell_3_5.setSizePolicy(sizePolicy)
        self.cell_3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_5.setObjectName(_fromUtf8("cell_3_5"))
        self.gridLayout_21.addWidget(self.cell_3_5, 0, 2, 1, 1)
        self.cell_5_4 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_4.sizePolicy().hasHeightForWidth())
        self.cell_5_4.setSizePolicy(sizePolicy)
        self.cell_5_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_4.setObjectName(_fromUtf8("cell_5_4"))
        self.gridLayout_21.addWidget(self.cell_5_4, 2, 1, 1, 1)
        self.cell_5_5 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_5.sizePolicy().hasHeightForWidth())
        self.cell_5_5.setSizePolicy(sizePolicy)
        self.cell_5_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_5.setObjectName(_fromUtf8("cell_5_5"))
        self.gridLayout_21.addWidget(self.cell_5_5, 2, 2, 1, 1)
        self.cell_4_3 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_3.sizePolicy().hasHeightForWidth())
        self.cell_4_3.setSizePolicy(sizePolicy)
        self.cell_4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_3.setObjectName(_fromUtf8("cell_4_3"))
        self.gridLayout_21.addWidget(self.cell_4_3, 1, 0, 1, 1)
        self.cell_3_3 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_3.sizePolicy().hasHeightForWidth())
        self.cell_3_3.setSizePolicy(sizePolicy)
        self.cell_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_3.setObjectName(_fromUtf8("cell_3_3"))
        self.gridLayout_21.addWidget(self.cell_3_3, 0, 0, 1, 1)
        self.cell_3_4 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_4.sizePolicy().hasHeightForWidth())
        self.cell_3_4.setSizePolicy(sizePolicy)
        self.cell_3_4.setText(_fromUtf8(""))
        self.cell_3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_4.setObjectName(_fromUtf8("cell_3_4"))
        self.gridLayout_21.addWidget(self.cell_3_4, 0, 1, 1, 1)
        self.cell_5_3 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_3.sizePolicy().hasHeightForWidth())
        self.cell_5_3.setSizePolicy(sizePolicy)
        self.cell_5_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_3.setObjectName(_fromUtf8("cell_5_3"))
        self.gridLayout_21.addWidget(self.cell_5_3, 2, 0, 1, 1)
        self.cell_4_5 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_5.sizePolicy().hasHeightForWidth())
        self.cell_4_5.setSizePolicy(sizePolicy)
        self.cell_4_5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_5.setObjectName(_fromUtf8("cell_4_5"))
        self.gridLayout_21.addWidget(self.cell_4_5, 1, 2, 1, 1)
        self.cell_4_4 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_4.sizePolicy().hasHeightForWidth())
        self.cell_4_4.setSizePolicy(sizePolicy)
        self.cell_4_4.setText(_fromUtf8(""))
        self.cell_4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_4.setObjectName(_fromUtf8("cell_4_4"))
        self.gridLayout_21.addWidget(self.cell_4_4, 1, 1, 1, 1)
        self.gridLayout_26.addWidget(self.frame_7, 1, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cell_0_1 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_1.sizePolicy().hasHeightForWidth())
        self.cell_0_1.setSizePolicy(sizePolicy)
        self.cell_0_1.setText(_fromUtf8(""))
        self.cell_0_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_1.setObjectName(_fromUtf8("cell_0_1"))
        self.gridLayout_3.addWidget(self.cell_0_1, 0, 1, 1, 1)
        self.cell_1_1 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_1.sizePolicy().hasHeightForWidth())
        self.cell_1_1.setSizePolicy(sizePolicy)
        self.cell_1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_1.setObjectName(_fromUtf8("cell_1_1"))
        self.gridLayout_3.addWidget(self.cell_1_1, 1, 1, 1, 1)
        self.cell_1_0 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_0.sizePolicy().hasHeightForWidth())
        self.cell_1_0.setSizePolicy(sizePolicy)
        self.cell_1_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_0.setObjectName(_fromUtf8("cell_1_0"))
        self.gridLayout_3.addWidget(self.cell_1_0, 1, 0, 1, 1)
        self.cell_2_0 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_0.sizePolicy().hasHeightForWidth())
        self.cell_2_0.setSizePolicy(sizePolicy)
        self.cell_2_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_0.setObjectName(_fromUtf8("cell_2_0"))
        self.gridLayout_3.addWidget(self.cell_2_0, 2, 0, 1, 1)
        self.cell_0_2 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_2.sizePolicy().hasHeightForWidth())
        self.cell_0_2.setSizePolicy(sizePolicy)
        self.cell_0_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_2.setObjectName(_fromUtf8("cell_0_2"))
        self.gridLayout_3.addWidget(self.cell_0_2, 0, 2, 1, 1)
        self.cell_2_1 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_1.sizePolicy().hasHeightForWidth())
        self.cell_2_1.setSizePolicy(sizePolicy)
        self.cell_2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_1.setObjectName(_fromUtf8("cell_2_1"))
        self.gridLayout_3.addWidget(self.cell_2_1, 2, 1, 1, 1)
        self.cell_2_2 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_2.sizePolicy().hasHeightForWidth())
        self.cell_2_2.setSizePolicy(sizePolicy)
        self.cell_2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_2.setObjectName(_fromUtf8("cell_2_2"))
        self.gridLayout_3.addWidget(self.cell_2_2, 2, 2, 1, 1)
        self.cell_1_2 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_2.sizePolicy().hasHeightForWidth())
        self.cell_1_2.setSizePolicy(sizePolicy)
        self.cell_1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_2.setObjectName(_fromUtf8("cell_1_2"))
        self.gridLayout_3.addWidget(self.cell_1_2, 1, 2, 1, 1)
        self.cell_0_0 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_0.sizePolicy().hasHeightForWidth())
        self.cell_0_0.setSizePolicy(sizePolicy)
        self.cell_0_0.setText(_fromUtf8(""))
        self.cell_0_0.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_0.setObjectName(_fromUtf8("cell_0_0"))
        self.gridLayout_3.addWidget(self.cell_0_0, 0, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_19 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_19.setMargin(0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.cell_0_6 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_6.sizePolicy().hasHeightForWidth())
        self.cell_0_6.setSizePolicy(sizePolicy)
        self.cell_0_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_6.setObjectName(_fromUtf8("cell_0_6"))
        self.gridLayout_19.addWidget(self.cell_0_6, 0, 0, 1, 1)
        self.cell_0_7 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_7.sizePolicy().hasHeightForWidth())
        self.cell_0_7.setSizePolicy(sizePolicy)
        self.cell_0_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_7.setObjectName(_fromUtf8("cell_0_7"))
        self.gridLayout_19.addWidget(self.cell_0_7, 0, 1, 1, 1)
        self.cell_1_7 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_7.sizePolicy().hasHeightForWidth())
        self.cell_1_7.setSizePolicy(sizePolicy)
        self.cell_1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_7.setObjectName(_fromUtf8("cell_1_7"))
        self.gridLayout_19.addWidget(self.cell_1_7, 1, 1, 1, 1)
        self.cell_1_6 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_6.sizePolicy().hasHeightForWidth())
        self.cell_1_6.setSizePolicy(sizePolicy)
        self.cell_1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_6.setObjectName(_fromUtf8("cell_1_6"))
        self.gridLayout_19.addWidget(self.cell_1_6, 1, 0, 1, 1)
        self.cell_2_6 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_6.sizePolicy().hasHeightForWidth())
        self.cell_2_6.setSizePolicy(sizePolicy)
        self.cell_2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_6.setObjectName(_fromUtf8("cell_2_6"))
        self.gridLayout_19.addWidget(self.cell_2_6, 2, 0, 1, 1)
        self.cell_2_7 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_7.sizePolicy().hasHeightForWidth())
        self.cell_2_7.setSizePolicy(sizePolicy)
        self.cell_2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_7.setObjectName(_fromUtf8("cell_2_7"))
        self.gridLayout_19.addWidget(self.cell_2_7, 2, 1, 1, 1)
        self.cell_2_8 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_8.sizePolicy().hasHeightForWidth())
        self.cell_2_8.setSizePolicy(sizePolicy)
        self.cell_2_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_2_8.setObjectName(_fromUtf8("cell_2_8"))
        self.gridLayout_19.addWidget(self.cell_2_8, 2, 2, 1, 1)
        self.cell_1_8 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_8.sizePolicy().hasHeightForWidth())
        self.cell_1_8.setSizePolicy(sizePolicy)
        self.cell_1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_1_8.setObjectName(_fromUtf8("cell_1_8"))
        self.gridLayout_19.addWidget(self.cell_1_8, 1, 2, 1, 1)
        self.cell_0_8 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_0_8.sizePolicy().hasHeightForWidth())
        self.cell_0_8.setSizePolicy(sizePolicy)
        self.cell_0_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_0_8.setObjectName(_fromUtf8("cell_0_8"))
        self.gridLayout_19.addWidget(self.cell_0_8, 0, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_5, 0, 2, 1, 1)
        self.frame_8 = QtGui.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_22 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_22.setMargin(0)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.cell_3_7 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_7.sizePolicy().hasHeightForWidth())
        self.cell_3_7.setSizePolicy(sizePolicy)
        self.cell_3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_7.setObjectName(_fromUtf8("cell_3_7"))
        self.gridLayout_22.addWidget(self.cell_3_7, 0, 1, 1, 1)
        self.cell_4_6 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_6.sizePolicy().hasHeightForWidth())
        self.cell_4_6.setSizePolicy(sizePolicy)
        self.cell_4_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_6.setObjectName(_fromUtf8("cell_4_6"))
        self.gridLayout_22.addWidget(self.cell_4_6, 1, 0, 1, 1)
        self.cell_3_8 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_8.sizePolicy().hasHeightForWidth())
        self.cell_3_8.setSizePolicy(sizePolicy)
        self.cell_3_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_8.setObjectName(_fromUtf8("cell_3_8"))
        self.gridLayout_22.addWidget(self.cell_3_8, 0, 2, 1, 1)
        self.cell_5_8 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_8.sizePolicy().hasHeightForWidth())
        self.cell_5_8.setSizePolicy(sizePolicy)
        self.cell_5_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_8.setObjectName(_fromUtf8("cell_5_8"))
        self.gridLayout_22.addWidget(self.cell_5_8, 2, 2, 1, 1)
        self.cell_5_7 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_7.sizePolicy().hasHeightForWidth())
        self.cell_5_7.setSizePolicy(sizePolicy)
        self.cell_5_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_7.setObjectName(_fromUtf8("cell_5_7"))
        self.gridLayout_22.addWidget(self.cell_5_7, 2, 1, 1, 1)
        self.cell_4_7 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_7.sizePolicy().hasHeightForWidth())
        self.cell_4_7.setSizePolicy(sizePolicy)
        self.cell_4_7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_7.setObjectName(_fromUtf8("cell_4_7"))
        self.gridLayout_22.addWidget(self.cell_4_7, 1, 1, 1, 1)
        self.cell_5_6 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_6.sizePolicy().hasHeightForWidth())
        self.cell_5_6.setSizePolicy(sizePolicy)
        self.cell_5_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_5_6.setObjectName(_fromUtf8("cell_5_6"))
        self.gridLayout_22.addWidget(self.cell_5_6, 2, 0, 1, 1)
        self.cell_3_6 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_6.sizePolicy().hasHeightForWidth())
        self.cell_3_6.setSizePolicy(sizePolicy)
        self.cell_3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_3_6.setObjectName(_fromUtf8("cell_3_6"))
        self.gridLayout_22.addWidget(self.cell_3_6, 0, 0, 1, 1)
        self.cell_4_8 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_8.sizePolicy().hasHeightForWidth())
        self.cell_4_8.setSizePolicy(sizePolicy)
        self.cell_4_8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell_4_8.setObjectName(_fromUtf8("cell_4_8"))
        self.gridLayout_22.addWidget(self.cell_4_8, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_8, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_13 = QtGui.QFrame(self.frame)
        self.frame_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_13)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineEdit_initial_puzzle = QtGui.QLineEdit(self.frame_13)
        self.lineEdit_initial_puzzle.setText(_fromUtf8(""))
        self.lineEdit_initial_puzzle.setObjectName(_fromUtf8("lineEdit_initial_puzzle"))
        self.gridLayout_4.addWidget(self.lineEdit_initial_puzzle, 0, 1, 1, 1)
        self.label_puzzle_str = QtGui.QLabel(self.frame_13)
        self.label_puzzle_str.setObjectName(_fromUtf8("label_puzzle_str"))
        self.gridLayout_4.addWidget(self.label_puzzle_str, 0, 0, 1, 1)
        self.label_2_solution_str = QtGui.QLabel(self.frame_13)
        self.label_2_solution_str.setObjectName(_fromUtf8("label_2_solution_str"))
        self.gridLayout_4.addWidget(self.label_2_solution_str, 1, 0, 1, 1)
        self.lineEdit_solved_puzzle = QtGui.QLineEdit(self.frame_13)
        self.lineEdit_solved_puzzle.setObjectName(_fromUtf8("lineEdit_solved_puzzle"))
        self.gridLayout_4.addWidget(self.lineEdit_solved_puzzle, 1, 1, 1, 1)
        self.lineEdit_multiple_solution = QtGui.QLineEdit(self.frame_13)
        self.lineEdit_multiple_solution.setObjectName(_fromUtf8("lineEdit_multiple_solution"))
        self.gridLayout_4.addWidget(self.lineEdit_multiple_solution, 2, 1, 1, 1)
        self.label_multiple_solution_contain = QtGui.QLabel(self.frame_13)
        self.label_multiple_solution_contain.setObjectName(_fromUtf8("label_multiple_solution_contain"))
        self.gridLayout_4.addWidget(self.label_multiple_solution_contain, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_13, 2, 0, 1, 1)
        self.frame_12 = QtGui.QFrame(self.frame)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_12)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_14 = QtGui.QFrame(self.frame_12)
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.pushButton_UA_prev_4 = QtGui.QPushButton(self.frame_14)
        self.pushButton_UA_prev_4.setGeometry(QtCore.QRect(0, 30, 51, 32))
        self.pushButton_UA_prev_4.setObjectName(_fromUtf8("pushButton_UA_prev_4"))
        self.pushButton_UA_next_4 = QtGui.QPushButton(self.frame_14)
        self.pushButton_UA_next_4.setGeometry(QtCore.QRect(50, 30, 51, 32))
        self.pushButton_UA_next_4.setObjectName(_fromUtf8("pushButton_UA_next_4"))
        self.label_3_UA_set_no_4 = QtGui.QLabel(self.frame_14)
        self.label_3_UA_set_no_4.setGeometry(QtCore.QRect(20, 10, 59, 16))
        self.label_3_UA_set_no_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3_UA_set_no_4.setObjectName(_fromUtf8("label_3_UA_set_no_4"))
        self.pushButton_UA_prev_6 = QtGui.QPushButton(self.frame_14)
        self.pushButton_UA_prev_6.setGeometry(QtCore.QRect(0, 30, 51, 32))
        self.pushButton_UA_prev_6.setObjectName(_fromUtf8("pushButton_UA_prev_6"))
        self.pushButton_UA_next_6 = QtGui.QPushButton(self.frame_14)
        self.pushButton_UA_next_6.setGeometry(QtCore.QRect(50, 30, 51, 32))
        self.pushButton_UA_next_6.setObjectName(_fromUtf8("pushButton_UA_next_6"))
        self.label_3_UA_set_no_6 = QtGui.QLabel(self.frame_14)
        self.label_3_UA_set_no_6.setGeometry(QtCore.QRect(20, 10, 59, 16))
        self.label_3_UA_set_no_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3_UA_set_no_6.setObjectName(_fromUtf8("label_3_UA_set_no_6"))
        self.gridLayout_5.addWidget(self.frame_14, 9, 1, 1, 1)
        self.pushButton_clear_all = QtGui.QPushButton(self.frame_12)
        self.pushButton_clear_all.setObjectName(_fromUtf8("pushButton_clear_all"))
        self.gridLayout_5.addWidget(self.pushButton_clear_all, 7, 1, 1, 1)
        self.pushButton_puzzle_to_grid = QtGui.QPushButton(self.frame_12)
        self.pushButton_puzzle_to_grid.setObjectName(_fromUtf8("pushButton_puzzle_to_grid"))
        self.gridLayout_5.addWidget(self.pushButton_puzzle_to_grid, 1, 1, 1, 1)
        self.comboBox_UA_size = QtGui.QComboBox(self.frame_12)
        self.comboBox_UA_size.setObjectName(_fromUtf8("comboBox_UA_size"))
        self.gridLayout_5.addWidget(self.comboBox_UA_size, 8, 1, 1, 1)
        self.pushButton_grid_to_puzzle = QtGui.QPushButton(self.frame_12)
        self.pushButton_grid_to_puzzle.setObjectName(_fromUtf8("pushButton_grid_to_puzzle"))
        self.gridLayout_5.addWidget(self.pushButton_grid_to_puzzle, 0, 1, 1, 1)
        self.pushButton_solution_to_grid = QtGui.QPushButton(self.frame_12)
        self.pushButton_solution_to_grid.setObjectName(_fromUtf8("pushButton_solution_to_grid"))
        self.gridLayout_5.addWidget(self.pushButton_solution_to_grid, 4, 1, 1, 1)
        self.pushButton_grid_to_solution = QtGui.QPushButton(self.frame_12)
        self.pushButton_grid_to_solution.setObjectName(_fromUtf8("pushButton_grid_to_solution"))
        self.gridLayout_5.addWidget(self.pushButton_grid_to_solution, 3, 1, 1, 1)
        self.pushButton_solve = QtGui.QPushButton(self.frame_12)
        self.pushButton_solve.setObjectName(_fromUtf8("pushButton_solve"))
        self.gridLayout_5.addWidget(self.pushButton_solve, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_12, 0, 1, 1, 1)
        self.frame_15 = QtGui.QFrame(self.frame)
        self.frame_15.setEnabled(True)
        self.frame_15.setAutoFillBackground(False)
        self.frame_15.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.pushButton_multiple_solutions_prev = QtGui.QPushButton(self.frame_15)
        self.pushButton_multiple_solutions_prev.setGeometry(QtCore.QRect(10, 40, 51, 32))
        self.pushButton_multiple_solutions_prev.setObjectName(_fromUtf8("pushButton_multiple_solutions_prev"))
        self.pushButton_multiple_solutions_next = QtGui.QPushButton(self.frame_15)
        self.pushButton_multiple_solutions_next.setGeometry(QtCore.QRect(60, 40, 51, 32))
        self.pushButton_multiple_solutions_next.setObjectName(_fromUtf8("pushButton_multiple_solutions_next"))
        self.label_multiple_solutions = QtGui.QLabel(self.frame_15)
        self.label_multiple_solutions.setGeometry(QtCore.QRect(30, 20, 59, 16))
        self.label_multiple_solutions.setAlignment(QtCore.Qt.AlignCenter)
        self.label_multiple_solutions.setObjectName(_fromUtf8("label_multiple_solutions"))
        self.gridLayout_2.addWidget(self.frame_15, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_puzzle_str.setText(_translate("MainWindow", "Puzzle", None))
        self.label_2_solution_str.setText(_translate("MainWindow", "Solution", None))
        self.label_multiple_solution_contain.setText(_translate("MainWindow", "Multiple Sol", None))
        self.pushButton_UA_prev_4.setText(_translate("MainWindow", "<", None))
        self.pushButton_UA_next_4.setText(_translate("MainWindow", ">", None))
        self.label_3_UA_set_no_4.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton_UA_prev_6.setText(_translate("MainWindow", "<", None))
        self.pushButton_UA_next_6.setText(_translate("MainWindow", ">", None))
        self.label_3_UA_set_no_6.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton_clear_all.setText(_translate("MainWindow", "Clear All", None))
        self.pushButton_puzzle_to_grid.setText(_translate("MainWindow", "Puzzle > Grid", None))
        self.pushButton_grid_to_puzzle.setText(_translate("MainWindow", "Grid > Puzzle", None))
        self.pushButton_solution_to_grid.setText(_translate("MainWindow", "Solution > Grid", None))
        self.pushButton_grid_to_solution.setText(_translate("MainWindow", "Grid > Solution", None))
        self.pushButton_solve.setText(_translate("MainWindow", "Solve", None))
        self.pushButton_multiple_solutions_prev.setText(_translate("MainWindow", "<", None))
        self.pushButton_multiple_solutions_next.setText(_translate("MainWindow", ">", None))
        self.label_multiple_solutions.setText(_translate("MainWindow", "TextLabel", None))

