# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 687)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_26 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cell_1_1 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_1.sizePolicy().hasHeightForWidth())
        self.cell_1_1.setSizePolicy(sizePolicy)
        self.cell_1_1.setText(_fromUtf8(""))
        self.cell_1_1.setObjectName(_fromUtf8("cell_1_1"))
        self.gridLayout_3.addWidget(self.cell_1_1, 0, 0, 1, 1)
        self.cell_1_2 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_2.sizePolicy().hasHeightForWidth())
        self.cell_1_2.setSizePolicy(sizePolicy)
        self.cell_1_2.setText(_fromUtf8(""))
        self.cell_1_2.setObjectName(_fromUtf8("cell_1_2"))
        self.gridLayout_3.addWidget(self.cell_1_2, 0, 1, 1, 1)
        self.cell_2_2 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_2.sizePolicy().hasHeightForWidth())
        self.cell_2_2.setSizePolicy(sizePolicy)
        self.cell_2_2.setObjectName(_fromUtf8("cell_2_2"))
        self.gridLayout_3.addWidget(self.cell_2_2, 1, 1, 1, 1)
        self.cell_2_1 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_1.sizePolicy().hasHeightForWidth())
        self.cell_2_1.setSizePolicy(sizePolicy)
        self.cell_2_1.setObjectName(_fromUtf8("cell_2_1"))
        self.gridLayout_3.addWidget(self.cell_2_1, 1, 0, 1, 1)
        self.cell_3_1 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_1.sizePolicy().hasHeightForWidth())
        self.cell_3_1.setSizePolicy(sizePolicy)
        self.cell_3_1.setObjectName(_fromUtf8("cell_3_1"))
        self.gridLayout_3.addWidget(self.cell_3_1, 2, 0, 1, 1)
        self.cell_3_3 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_3.sizePolicy().hasHeightForWidth())
        self.cell_3_3.setSizePolicy(sizePolicy)
        self.cell_3_3.setObjectName(_fromUtf8("cell_3_3"))
        self.gridLayout_3.addWidget(self.cell_3_3, 2, 2, 1, 1)
        self.cell_3_2 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_2.sizePolicy().hasHeightForWidth())
        self.cell_3_2.setSizePolicy(sizePolicy)
        self.cell_3_2.setObjectName(_fromUtf8("cell_3_2"))
        self.gridLayout_3.addWidget(self.cell_3_2, 2, 1, 1, 1)
        self.cell_1_3 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_3.sizePolicy().hasHeightForWidth())
        self.cell_1_3.setSizePolicy(sizePolicy)
        self.cell_1_3.setObjectName(_fromUtf8("cell_1_3"))
        self.gridLayout_3.addWidget(self.cell_1_3, 0, 2, 1, 1)
        self.cell_2_3 = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_3.sizePolicy().hasHeightForWidth())
        self.cell_2_3.setSizePolicy(sizePolicy)
        self.cell_2_3.setObjectName(_fromUtf8("cell_2_3"))
        self.gridLayout_3.addWidget(self.cell_2_3, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_18 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_18.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.cell_1_4 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_4.sizePolicy().hasHeightForWidth())
        self.cell_1_4.setSizePolicy(sizePolicy)
        self.cell_1_4.setObjectName(_fromUtf8("cell_1_4"))
        self.gridLayout_18.addWidget(self.cell_1_4, 0, 0, 1, 1)
        self.cell_1_5 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_5.sizePolicy().hasHeightForWidth())
        self.cell_1_5.setSizePolicy(sizePolicy)
        self.cell_1_5.setObjectName(_fromUtf8("cell_1_5"))
        self.gridLayout_18.addWidget(self.cell_1_5, 0, 1, 1, 1)
        self.cell_2_5 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_5.sizePolicy().hasHeightForWidth())
        self.cell_2_5.setSizePolicy(sizePolicy)
        self.cell_2_5.setObjectName(_fromUtf8("cell_2_5"))
        self.gridLayout_18.addWidget(self.cell_2_5, 1, 1, 1, 1)
        self.cell_2_4 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_4.sizePolicy().hasHeightForWidth())
        self.cell_2_4.setSizePolicy(sizePolicy)
        self.cell_2_4.setObjectName(_fromUtf8("cell_2_4"))
        self.gridLayout_18.addWidget(self.cell_2_4, 1, 0, 1, 1)
        self.cell_3_4 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_4.sizePolicy().hasHeightForWidth())
        self.cell_3_4.setSizePolicy(sizePolicy)
        self.cell_3_4.setObjectName(_fromUtf8("cell_3_4"))
        self.gridLayout_18.addWidget(self.cell_3_4, 2, 0, 1, 1)
        self.cell_3_6 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_6.sizePolicy().hasHeightForWidth())
        self.cell_3_6.setSizePolicy(sizePolicy)
        self.cell_3_6.setObjectName(_fromUtf8("cell_3_6"))
        self.gridLayout_18.addWidget(self.cell_3_6, 2, 2, 1, 1)
        self.cell_3_5 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_5.sizePolicy().hasHeightForWidth())
        self.cell_3_5.setSizePolicy(sizePolicy)
        self.cell_3_5.setObjectName(_fromUtf8("cell_3_5"))
        self.gridLayout_18.addWidget(self.cell_3_5, 2, 1, 1, 1)
        self.cell_1_6 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_6.sizePolicy().hasHeightForWidth())
        self.cell_1_6.setSizePolicy(sizePolicy)
        self.cell_1_6.setObjectName(_fromUtf8("cell_1_6"))
        self.gridLayout_18.addWidget(self.cell_1_6, 0, 2, 1, 1)
        self.cell_2_6 = QtGui.QLineEdit(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_6.sizePolicy().hasHeightForWidth())
        self.cell_2_6.setSizePolicy(sizePolicy)
        self.cell_2_6.setObjectName(_fromUtf8("cell_2_6"))
        self.gridLayout_18.addWidget(self.cell_2_6, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_4, 0, 1, 1, 1)
        self.frame_5 = QtGui.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_19 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_19.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.cell_1_7 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_7.sizePolicy().hasHeightForWidth())
        self.cell_1_7.setSizePolicy(sizePolicy)
        self.cell_1_7.setObjectName(_fromUtf8("cell_1_7"))
        self.gridLayout_19.addWidget(self.cell_1_7, 0, 0, 1, 1)
        self.cell_1_8 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_8.sizePolicy().hasHeightForWidth())
        self.cell_1_8.setSizePolicy(sizePolicy)
        self.cell_1_8.setObjectName(_fromUtf8("cell_1_8"))
        self.gridLayout_19.addWidget(self.cell_1_8, 0, 1, 1, 1)
        self.cell_2_8 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_8.sizePolicy().hasHeightForWidth())
        self.cell_2_8.setSizePolicy(sizePolicy)
        self.cell_2_8.setObjectName(_fromUtf8("cell_2_8"))
        self.gridLayout_19.addWidget(self.cell_2_8, 1, 1, 1, 1)
        self.cell_2_7 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_7.sizePolicy().hasHeightForWidth())
        self.cell_2_7.setSizePolicy(sizePolicy)
        self.cell_2_7.setObjectName(_fromUtf8("cell_2_7"))
        self.gridLayout_19.addWidget(self.cell_2_7, 1, 0, 1, 1)
        self.cell_3_7 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_7.sizePolicy().hasHeightForWidth())
        self.cell_3_7.setSizePolicy(sizePolicy)
        self.cell_3_7.setObjectName(_fromUtf8("cell_3_7"))
        self.gridLayout_19.addWidget(self.cell_3_7, 2, 0, 1, 1)
        self.cell_3_8 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_8.sizePolicy().hasHeightForWidth())
        self.cell_3_8.setSizePolicy(sizePolicy)
        self.cell_3_8.setObjectName(_fromUtf8("cell_3_8"))
        self.gridLayout_19.addWidget(self.cell_3_8, 2, 1, 1, 1)
        self.cell_3_9 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_3_9.sizePolicy().hasHeightForWidth())
        self.cell_3_9.setSizePolicy(sizePolicy)
        self.cell_3_9.setObjectName(_fromUtf8("cell_3_9"))
        self.gridLayout_19.addWidget(self.cell_3_9, 2, 2, 1, 1)
        self.cell_2_9 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_2_9.sizePolicy().hasHeightForWidth())
        self.cell_2_9.setSizePolicy(sizePolicy)
        self.cell_2_9.setObjectName(_fromUtf8("cell_2_9"))
        self.gridLayout_19.addWidget(self.cell_2_9, 1, 2, 1, 1)
        self.cell_1_9 = QtGui.QLineEdit(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_1_9.sizePolicy().hasHeightForWidth())
        self.cell_1_9.setSizePolicy(sizePolicy)
        self.cell_1_9.setObjectName(_fromUtf8("cell_1_9"))
        self.gridLayout_19.addWidget(self.cell_1_9, 0, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_5, 0, 2, 1, 1)
        self.frame_6 = QtGui.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_20.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.cell_4_1 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_1.sizePolicy().hasHeightForWidth())
        self.cell_4_1.setSizePolicy(sizePolicy)
        self.cell_4_1.setObjectName(_fromUtf8("cell_4_1"))
        self.gridLayout_20.addWidget(self.cell_4_1, 0, 0, 1, 1)
        self.cell_4_2 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_2.sizePolicy().hasHeightForWidth())
        self.cell_4_2.setSizePolicy(sizePolicy)
        self.cell_4_2.setObjectName(_fromUtf8("cell_4_2"))
        self.gridLayout_20.addWidget(self.cell_4_2, 0, 1, 1, 1)
        self.cell_5_2 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_2.sizePolicy().hasHeightForWidth())
        self.cell_5_2.setSizePolicy(sizePolicy)
        self.cell_5_2.setObjectName(_fromUtf8("cell_5_2"))
        self.gridLayout_20.addWidget(self.cell_5_2, 1, 1, 1, 1)
        self.cell_5_1 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_1.sizePolicy().hasHeightForWidth())
        self.cell_5_1.setSizePolicy(sizePolicy)
        self.cell_5_1.setObjectName(_fromUtf8("cell_5_1"))
        self.gridLayout_20.addWidget(self.cell_5_1, 1, 0, 1, 1)
        self.cell_6_1 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_1.sizePolicy().hasHeightForWidth())
        self.cell_6_1.setSizePolicy(sizePolicy)
        self.cell_6_1.setObjectName(_fromUtf8("cell_6_1"))
        self.gridLayout_20.addWidget(self.cell_6_1, 2, 0, 1, 1)
        self.cell_6_3 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_3.sizePolicy().hasHeightForWidth())
        self.cell_6_3.setSizePolicy(sizePolicy)
        self.cell_6_3.setObjectName(_fromUtf8("cell_6_3"))
        self.gridLayout_20.addWidget(self.cell_6_3, 2, 2, 1, 1)
        self.cell_6_2 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_2.sizePolicy().hasHeightForWidth())
        self.cell_6_2.setSizePolicy(sizePolicy)
        self.cell_6_2.setObjectName(_fromUtf8("cell_6_2"))
        self.gridLayout_20.addWidget(self.cell_6_2, 2, 1, 1, 1)
        self.cell_4_3 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_3.sizePolicy().hasHeightForWidth())
        self.cell_4_3.setSizePolicy(sizePolicy)
        self.cell_4_3.setObjectName(_fromUtf8("cell_4_3"))
        self.gridLayout_20.addWidget(self.cell_4_3, 0, 2, 1, 1)
        self.cell_5_3 = QtGui.QLineEdit(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_3.sizePolicy().hasHeightForWidth())
        self.cell_5_3.setSizePolicy(sizePolicy)
        self.cell_5_3.setObjectName(_fromUtf8("cell_5_3"))
        self.gridLayout_20.addWidget(self.cell_5_3, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_7 = QtGui.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_21.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.cell_4_4 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_4.sizePolicy().hasHeightForWidth())
        self.cell_4_4.setSizePolicy(sizePolicy)
        self.cell_4_4.setObjectName(_fromUtf8("cell_4_4"))
        self.gridLayout_21.addWidget(self.cell_4_4, 0, 0, 1, 1)
        self.cell_4_5 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_5.sizePolicy().hasHeightForWidth())
        self.cell_4_5.setSizePolicy(sizePolicy)
        self.cell_4_5.setObjectName(_fromUtf8("cell_4_5"))
        self.gridLayout_21.addWidget(self.cell_4_5, 0, 1, 1, 1)
        self.cell_5_5 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_5.sizePolicy().hasHeightForWidth())
        self.cell_5_5.setSizePolicy(sizePolicy)
        self.cell_5_5.setObjectName(_fromUtf8("cell_5_5"))
        self.gridLayout_21.addWidget(self.cell_5_5, 1, 1, 1, 1)
        self.cell_5_4 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_4.sizePolicy().hasHeightForWidth())
        self.cell_5_4.setSizePolicy(sizePolicy)
        self.cell_5_4.setObjectName(_fromUtf8("cell_5_4"))
        self.gridLayout_21.addWidget(self.cell_5_4, 1, 0, 1, 1)
        self.cell_6_4 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_4.sizePolicy().hasHeightForWidth())
        self.cell_6_4.setSizePolicy(sizePolicy)
        self.cell_6_4.setObjectName(_fromUtf8("cell_6_4"))
        self.gridLayout_21.addWidget(self.cell_6_4, 2, 0, 1, 1)
        self.cell_6_6 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_6.sizePolicy().hasHeightForWidth())
        self.cell_6_6.setSizePolicy(sizePolicy)
        self.cell_6_6.setObjectName(_fromUtf8("cell_6_6"))
        self.gridLayout_21.addWidget(self.cell_6_6, 2, 2, 1, 1)
        self.cell_6_5 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_5.sizePolicy().hasHeightForWidth())
        self.cell_6_5.setSizePolicy(sizePolicy)
        self.cell_6_5.setObjectName(_fromUtf8("cell_6_5"))
        self.gridLayout_21.addWidget(self.cell_6_5, 2, 1, 1, 1)
        self.cell_4_6 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_6.sizePolicy().hasHeightForWidth())
        self.cell_4_6.setSizePolicy(sizePolicy)
        self.cell_4_6.setObjectName(_fromUtf8("cell_4_6"))
        self.gridLayout_21.addWidget(self.cell_4_6, 0, 2, 1, 1)
        self.cell_5_6 = QtGui.QLineEdit(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_6.sizePolicy().hasHeightForWidth())
        self.cell_5_6.setSizePolicy(sizePolicy)
        self.cell_5_6.setObjectName(_fromUtf8("cell_5_6"))
        self.gridLayout_21.addWidget(self.cell_5_6, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_7, 1, 1, 1, 1)
        self.frame_8 = QtGui.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_22 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_22.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.cell_4_7 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_7.sizePolicy().hasHeightForWidth())
        self.cell_4_7.setSizePolicy(sizePolicy)
        self.cell_4_7.setObjectName(_fromUtf8("cell_4_7"))
        self.gridLayout_22.addWidget(self.cell_4_7, 0, 0, 1, 1)
        self.cell_4_8 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_8.sizePolicy().hasHeightForWidth())
        self.cell_4_8.setSizePolicy(sizePolicy)
        self.cell_4_8.setObjectName(_fromUtf8("cell_4_8"))
        self.gridLayout_22.addWidget(self.cell_4_8, 0, 1, 1, 1)
        self.cell_5_8 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_8.sizePolicy().hasHeightForWidth())
        self.cell_5_8.setSizePolicy(sizePolicy)
        self.cell_5_8.setObjectName(_fromUtf8("cell_5_8"))
        self.gridLayout_22.addWidget(self.cell_5_8, 1, 1, 1, 1)
        self.cell_5_7 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_7.sizePolicy().hasHeightForWidth())
        self.cell_5_7.setSizePolicy(sizePolicy)
        self.cell_5_7.setObjectName(_fromUtf8("cell_5_7"))
        self.gridLayout_22.addWidget(self.cell_5_7, 1, 0, 1, 1)
        self.cell_6_7 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_7.sizePolicy().hasHeightForWidth())
        self.cell_6_7.setSizePolicy(sizePolicy)
        self.cell_6_7.setObjectName(_fromUtf8("cell_6_7"))
        self.gridLayout_22.addWidget(self.cell_6_7, 2, 0, 1, 1)
        self.cell_6_9 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_9.sizePolicy().hasHeightForWidth())
        self.cell_6_9.setSizePolicy(sizePolicy)
        self.cell_6_9.setObjectName(_fromUtf8("cell_6_9"))
        self.gridLayout_22.addWidget(self.cell_6_9, 2, 2, 1, 1)
        self.cell_6_8 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_6_8.sizePolicy().hasHeightForWidth())
        self.cell_6_8.setSizePolicy(sizePolicy)
        self.cell_6_8.setObjectName(_fromUtf8("cell_6_8"))
        self.gridLayout_22.addWidget(self.cell_6_8, 2, 1, 1, 1)
        self.cell_4_9 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_4_9.sizePolicy().hasHeightForWidth())
        self.cell_4_9.setSizePolicy(sizePolicy)
        self.cell_4_9.setObjectName(_fromUtf8("cell_4_9"))
        self.gridLayout_22.addWidget(self.cell_4_9, 0, 2, 1, 1)
        self.cell_5_9 = QtGui.QLineEdit(self.frame_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_5_9.sizePolicy().hasHeightForWidth())
        self.cell_5_9.setSizePolicy(sizePolicy)
        self.cell_5_9.setObjectName(_fromUtf8("cell_5_9"))
        self.gridLayout_22.addWidget(self.cell_5_9, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_8, 1, 2, 1, 1)
        self.frame_9 = QtGui.QFrame(self.frame_2)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_23 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_23.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.cell_7_1 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_1.sizePolicy().hasHeightForWidth())
        self.cell_7_1.setSizePolicy(sizePolicy)
        self.cell_7_1.setObjectName(_fromUtf8("cell_7_1"))
        self.gridLayout_23.addWidget(self.cell_7_1, 0, 0, 1, 1)
        self.cell_7_2 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_2.sizePolicy().hasHeightForWidth())
        self.cell_7_2.setSizePolicy(sizePolicy)
        self.cell_7_2.setObjectName(_fromUtf8("cell_7_2"))
        self.gridLayout_23.addWidget(self.cell_7_2, 0, 1, 1, 1)
        self.cell_8_2 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_2.sizePolicy().hasHeightForWidth())
        self.cell_8_2.setSizePolicy(sizePolicy)
        self.cell_8_2.setObjectName(_fromUtf8("cell_8_2"))
        self.gridLayout_23.addWidget(self.cell_8_2, 1, 1, 1, 1)
        self.cell_8_1 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_1.sizePolicy().hasHeightForWidth())
        self.cell_8_1.setSizePolicy(sizePolicy)
        self.cell_8_1.setObjectName(_fromUtf8("cell_8_1"))
        self.gridLayout_23.addWidget(self.cell_8_1, 1, 0, 1, 1)
        self.cell_9_1 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_1.sizePolicy().hasHeightForWidth())
        self.cell_9_1.setSizePolicy(sizePolicy)
        self.cell_9_1.setObjectName(_fromUtf8("cell_9_1"))
        self.gridLayout_23.addWidget(self.cell_9_1, 2, 0, 1, 1)
        self.cell_9_3 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_3.sizePolicy().hasHeightForWidth())
        self.cell_9_3.setSizePolicy(sizePolicy)
        self.cell_9_3.setObjectName(_fromUtf8("cell_9_3"))
        self.gridLayout_23.addWidget(self.cell_9_3, 2, 2, 1, 1)
        self.cell_9_2 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_2.sizePolicy().hasHeightForWidth())
        self.cell_9_2.setSizePolicy(sizePolicy)
        self.cell_9_2.setObjectName(_fromUtf8("cell_9_2"))
        self.gridLayout_23.addWidget(self.cell_9_2, 2, 1, 1, 1)
        self.cell_7_3 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_3.sizePolicy().hasHeightForWidth())
        self.cell_7_3.setSizePolicy(sizePolicy)
        self.cell_7_3.setObjectName(_fromUtf8("cell_7_3"))
        self.gridLayout_23.addWidget(self.cell_7_3, 0, 2, 1, 1)
        self.cell_8_3 = QtGui.QLineEdit(self.frame_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_3.sizePolicy().hasHeightForWidth())
        self.cell_8_3.setSizePolicy(sizePolicy)
        self.cell_8_3.setObjectName(_fromUtf8("cell_8_3"))
        self.gridLayout_23.addWidget(self.cell_8_3, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_9, 2, 0, 1, 1)
        self.frame_10 = QtGui.QFrame(self.frame_2)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.gridLayout_24 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_24.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.cell_7_4 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_4.sizePolicy().hasHeightForWidth())
        self.cell_7_4.setSizePolicy(sizePolicy)
        self.cell_7_4.setObjectName(_fromUtf8("cell_7_4"))
        self.gridLayout_24.addWidget(self.cell_7_4, 0, 0, 1, 1)
        self.cell_7_5 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_5.sizePolicy().hasHeightForWidth())
        self.cell_7_5.setSizePolicy(sizePolicy)
        self.cell_7_5.setObjectName(_fromUtf8("cell_7_5"))
        self.gridLayout_24.addWidget(self.cell_7_5, 0, 1, 1, 1)
        self.cell_8_5 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_5.sizePolicy().hasHeightForWidth())
        self.cell_8_5.setSizePolicy(sizePolicy)
        self.cell_8_5.setObjectName(_fromUtf8("cell_8_5"))
        self.gridLayout_24.addWidget(self.cell_8_5, 1, 1, 1, 1)
        self.cell_8_4 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_4.sizePolicy().hasHeightForWidth())
        self.cell_8_4.setSizePolicy(sizePolicy)
        self.cell_8_4.setObjectName(_fromUtf8("cell_8_4"))
        self.gridLayout_24.addWidget(self.cell_8_4, 1, 0, 1, 1)
        self.cell_9_4 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_4.sizePolicy().hasHeightForWidth())
        self.cell_9_4.setSizePolicy(sizePolicy)
        self.cell_9_4.setObjectName(_fromUtf8("cell_9_4"))
        self.gridLayout_24.addWidget(self.cell_9_4, 2, 0, 1, 1)
        self.cell_9_6 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_6.sizePolicy().hasHeightForWidth())
        self.cell_9_6.setSizePolicy(sizePolicy)
        self.cell_9_6.setObjectName(_fromUtf8("cell_9_6"))
        self.gridLayout_24.addWidget(self.cell_9_6, 2, 2, 1, 1)
        self.cell_9_5 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_5.sizePolicy().hasHeightForWidth())
        self.cell_9_5.setSizePolicy(sizePolicy)
        self.cell_9_5.setObjectName(_fromUtf8("cell_9_5"))
        self.gridLayout_24.addWidget(self.cell_9_5, 2, 1, 1, 1)
        self.cell_7_6 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_6.sizePolicy().hasHeightForWidth())
        self.cell_7_6.setSizePolicy(sizePolicy)
        self.cell_7_6.setObjectName(_fromUtf8("cell_7_6"))
        self.gridLayout_24.addWidget(self.cell_7_6, 0, 2, 1, 1)
        self.cell_8_6 = QtGui.QLineEdit(self.frame_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_6.sizePolicy().hasHeightForWidth())
        self.cell_8_6.setSizePolicy(sizePolicy)
        self.cell_8_6.setObjectName(_fromUtf8("cell_8_6"))
        self.gridLayout_24.addWidget(self.cell_8_6, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_10, 2, 1, 1, 1)
        self.frame_11 = QtGui.QFrame(self.frame_2)
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.gridLayout_25 = QtGui.QGridLayout(self.frame_11)
        self.gridLayout_25.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.cell_7_7 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_7.sizePolicy().hasHeightForWidth())
        self.cell_7_7.setSizePolicy(sizePolicy)
        self.cell_7_7.setObjectName(_fromUtf8("cell_7_7"))
        self.gridLayout_25.addWidget(self.cell_7_7, 0, 0, 1, 1)
        self.cell_7_8 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_8.sizePolicy().hasHeightForWidth())
        self.cell_7_8.setSizePolicy(sizePolicy)
        self.cell_7_8.setObjectName(_fromUtf8("cell_7_8"))
        self.gridLayout_25.addWidget(self.cell_7_8, 0, 1, 1, 1)
        self.cell_8_8 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_8.sizePolicy().hasHeightForWidth())
        self.cell_8_8.setSizePolicy(sizePolicy)
        self.cell_8_8.setObjectName(_fromUtf8("cell_8_8"))
        self.gridLayout_25.addWidget(self.cell_8_8, 1, 1, 1, 1)
        self.cell_8_7 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_7.sizePolicy().hasHeightForWidth())
        self.cell_8_7.setSizePolicy(sizePolicy)
        self.cell_8_7.setObjectName(_fromUtf8("cell_8_7"))
        self.gridLayout_25.addWidget(self.cell_8_7, 1, 0, 1, 1)
        self.cell_9_7 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_7.sizePolicy().hasHeightForWidth())
        self.cell_9_7.setSizePolicy(sizePolicy)
        self.cell_9_7.setObjectName(_fromUtf8("cell_9_7"))
        self.gridLayout_25.addWidget(self.cell_9_7, 2, 0, 1, 1)
        self.cell_9_9 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_9.sizePolicy().hasHeightForWidth())
        self.cell_9_9.setSizePolicy(sizePolicy)
        self.cell_9_9.setObjectName(_fromUtf8("cell_9_9"))
        self.gridLayout_25.addWidget(self.cell_9_9, 2, 2, 1, 1)
        self.cell_9_8 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_9_8.sizePolicy().hasHeightForWidth())
        self.cell_9_8.setSizePolicy(sizePolicy)
        self.cell_9_8.setObjectName(_fromUtf8("cell_9_8"))
        self.gridLayout_25.addWidget(self.cell_9_8, 2, 1, 1, 1)
        self.cell_7_9 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_7_9.sizePolicy().hasHeightForWidth())
        self.cell_7_9.setSizePolicy(sizePolicy)
        self.cell_7_9.setObjectName(_fromUtf8("cell_7_9"))
        self.gridLayout_25.addWidget(self.cell_7_9, 0, 2, 1, 1)
        self.cell_8_9 = QtGui.QLineEdit(self.frame_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell_8_9.sizePolicy().hasHeightForWidth())
        self.cell_8_9.setSizePolicy(sizePolicy)
        self.cell_8_9.setObjectName(_fromUtf8("cell_8_9"))
        self.gridLayout_25.addWidget(self.cell_8_9, 1, 2, 1, 1)
        self.gridLayout_26.addWidget(self.frame_11, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_12 = QtGui.QFrame(self.frame)
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.gridLayout_27 = QtGui.QGridLayout(self.frame_12)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.confirm_button = QtGui.QPushButton(self.frame_12)
        self.confirm_button.setObjectName(_fromUtf8("confirm_button"))
        self.gridLayout_27.addWidget(self.confirm_button, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_12, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.confirm_button.setText(_translate("MainWindow", "Confirm", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

