from PyQt4 import QtGui
import sys

import MainUi

class MainApp(QtGui.QMainWindow, MainUi.Ui_MainWindow):

	def __init__(self, parent=None):
		super(MainApp, self).__init__(parent)
		self.setupUi(self)

		#self.pushButton_solve.clicked.connect(self.xxx)
		self.pushButton_load_puzzle.clicked.connect(self.initial_puz_set_cell)
		self.pushButton_clear_all.clicked.connect(self.delete_all_cells)

	def return_zero_if_empty(self, cell_text):
		if cell_text == "":
			return "0"
		else:
			return cell_text

	def delete_all_cells(self):
		self.cell_0_0.setText("")
		self.cell_0_1.setText("")
		self.cell_0_2.setText("")
		self.cell_0_3.setText("")
		self.cell_0_4.setText("")
		self.cell_0_5.setText("")
		self.cell_0_6.setText("")
		self.cell_0_7.setText("")
		self.cell_0_8.setText("")

		self.cell_1_0.setText("")
		self.cell_1_1.setText("")
		self.cell_1_2.setText("")
		self.cell_1_3.setText("")
		self.cell_1_4.setText("")
		self.cell_1_5.setText("")
		self.cell_1_6.setText("")
		self.cell_1_7.setText("")
		self.cell_1_8.setText("")

		self.cell_2_0.setText("")
		self.cell_2_1.setText("")
		self.cell_2_2.setText("")
		self.cell_2_3.setText("")
		self.cell_2_4.setText("")
		self.cell_2_5.setText("")
		self.cell_2_6.setText("")
		self.cell_2_7.setText("")
		self.cell_2_8.setText("")

		self.cell_3_0.setText("")
		self.cell_3_1.setText("")
		self.cell_3_2.setText("")
		self.cell_3_3.setText("")
		self.cell_3_4.setText("")
		self.cell_3_5.setText("")
		self.cell_3_6.setText("")
		self.cell_3_7.setText("")
		self.cell_3_8.setText("")

		self.cell_4_0.setText("")
		self.cell_4_1.setText("")
		self.cell_4_2.setText("")
		self.cell_4_3.setText("")
		self.cell_4_4.setText("")
		self.cell_4_5.setText("")
		self.cell_4_6.setText("")
		self.cell_4_7.setText("")
		self.cell_4_8.setText("")

		self.cell_5_0.setText("")
		self.cell_5_1.setText("")
		self.cell_5_2.setText("")
		self.cell_5_3.setText("")
		self.cell_5_4.setText("")
		self.cell_5_5.setText("")
		self.cell_5_6.setText("")
		self.cell_5_7.setText("")
		self.cell_5_8.setText("")

		self.cell_6_0.setText("")
		self.cell_6_1.setText("")
		self.cell_6_2.setText("")
		self.cell_6_3.setText("")
		self.cell_6_4.setText("")
		self.cell_6_5.setText("")
		self.cell_6_6.setText("")
		self.cell_6_7.setText("")
		self.cell_6_8.setText("")

		self.cell_7_0.setText("")
		self.cell_7_1.setText("")
		self.cell_7_2.setText("")
		self.cell_7_3.setText("")
		self.cell_7_4.setText("")
		self.cell_7_5.setText("")
		self.cell_7_6.setText("")
		self.cell_7_7.setText("")
		self.cell_7_8.setText("")

		self.cell_8_0.setText("")
		self.cell_8_1.setText("")
		self.cell_8_2.setText("")
		self.cell_8_3.setText("")
		self.cell_8_4.setText("")
		self.cell_8_5.setText("")
		self.cell_8_6.setText("")
		self.cell_8_7.setText("")
		self.cell_8_8.setText("")

	def cell_set_initial_puz(self):
		result_string = ""

		result_string = result_string + self.return_zero_if_empty(self.cell_0_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_1_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_2_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_3_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_4_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_5_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_6_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_7_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_8_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_8.text())

		self.lineEdit_initial_puzzle.setText(result_string)

	def all_cells_empty(self):
		result_string = ""

		result_string = result_string + self.return_zero_if_empty(self.cell_0_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_0_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_1_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_1_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_2_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_2_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_3_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_3_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_4_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_4_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_5_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_5_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_6_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_6_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_7_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_7_8.text())

		result_string = result_string + self.return_zero_if_empty(self.cell_8_0.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_1.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_2.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_3.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_4.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_5.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_6.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_7.text())
		result_string = result_string + self.return_zero_if_empty(self.cell_8_8.text())

		return result_string

	def initial_puz_set_cell(self):

		if len(self.lineEdit_initial_puzzle.text()) != 0:
			puzzle = str(self.lineEdit_initial_puzzle.text())

			self.cell_0_0.setText(puzzle[0])
			self.cell_0_1.setText(puzzle[1])
			self.cell_0_2.setText(puzzle[2])
			self.cell_0_3.setText(puzzle[3])
			self.cell_0_4.setText(puzzle[4])
			self.cell_0_5.setText(puzzle[5])
			self.cell_0_6.setText(puzzle[6])
			self.cell_0_7.setText(puzzle[7])
			self.cell_0_8.setText(puzzle[8])

			self.cell_1_0.setText(puzzle[9])
			self.cell_1_1.setText(puzzle[10])
			self.cell_1_2.setText(puzzle[11])
			self.cell_1_3.setText(puzzle[12])
			self.cell_1_4.setText(puzzle[13])
			self.cell_1_5.setText(puzzle[14])
			self.cell_1_6.setText(puzzle[15])
			self.cell_1_7.setText(puzzle[16])
			self.cell_1_8.setText(puzzle[17])

			self.cell_2_0.setText(puzzle[18])
			self.cell_2_1.setText(puzzle[19])
			self.cell_2_2.setText(puzzle[20])
			self.cell_2_3.setText(puzzle[21])
			self.cell_2_4.setText(puzzle[22])
			self.cell_2_5.setText(puzzle[23])
			self.cell_2_6.setText(puzzle[24])
			self.cell_2_7.setText(puzzle[25])
			self.cell_2_8.setText(puzzle[26])

			self.cell_3_0.setText(puzzle[27])
			self.cell_3_1.setText(puzzle[28])
			self.cell_3_2.setText(puzzle[29])
			self.cell_3_3.setText(puzzle[30])
			self.cell_3_4.setText(puzzle[31])
			self.cell_3_5.setText(puzzle[32])
			self.cell_3_6.setText(puzzle[33])
			self.cell_3_7.setText(puzzle[34])
			self.cell_3_8.setText(puzzle[35])

			self.cell_4_0.setText(puzzle[36])
			self.cell_4_1.setText(puzzle[37])
			self.cell_4_2.setText(puzzle[38])
			self.cell_4_3.setText(puzzle[39])
			self.cell_4_4.setText(puzzle[40])
			self.cell_4_5.setText(puzzle[41])
			self.cell_4_6.setText(puzzle[42])
			self.cell_4_7.setText(puzzle[43])
			self.cell_4_8.setText(puzzle[44])

			self.cell_5_0.setText(puzzle[45])
			self.cell_5_1.setText(puzzle[46])
			self.cell_5_2.setText(puzzle[47])
			self.cell_5_3.setText(puzzle[48])
			self.cell_5_4.setText(puzzle[49])
			self.cell_5_5.setText(puzzle[50])
			self.cell_5_6.setText(puzzle[51])
			self.cell_5_7.setText(puzzle[52])
			self.cell_5_8.setText(puzzle[53])

			self.cell_6_0.setText(puzzle[54])
			self.cell_6_1.setText(puzzle[55])
			self.cell_6_2.setText(puzzle[56])
			self.cell_6_3.setText(puzzle[57])
			self.cell_6_4.setText(puzzle[58])
			self.cell_6_5.setText(puzzle[59])
			self.cell_6_6.setText(puzzle[60])
			self.cell_6_7.setText(puzzle[61])
			self.cell_6_8.setText(puzzle[62])

			self.cell_7_0.setText(puzzle[63])
			self.cell_7_1.setText(puzzle[64])
			self.cell_7_2.setText(puzzle[65])
			self.cell_7_3.setText(puzzle[66])
			self.cell_7_4.setText(puzzle[67])
			self.cell_7_5.setText(puzzle[68])
			self.cell_7_6.setText(puzzle[69])
			self.cell_7_7.setText(puzzle[70])
			self.cell_7_8.setText(puzzle[71])

			self.cell_8_0.setText(puzzle[72])
			self.cell_8_1.setText(puzzle[73])
			self.cell_8_2.setText(puzzle[74])
			self.cell_8_3.setText(puzzle[75])
			self.cell_8_4.setText(puzzle[76])
			self.cell_8_5.setText(puzzle[77])
			self.cell_8_6.setText(puzzle[78])
			self.cell_8_7.setText(puzzle[79])
			self.cell_8_8.setText(puzzle[80])

		elif self.all_cells_empty() == "000000000000000000000000000000000000000000000000000000000000000000000000000000000":
			return

		else:
			self.cell_set_initial_puz()



def main():
	app = QtGui.QApplication(sys.argv)
	form = MainApp()
	form.show()
	app.exec_()



if __name__ == '__main__':
	main()
